# development:
#   adapter: postgresql
#   database: ninety_nine_cats_dev
#   host: 127.0.0.1
#   pool: 5
#   timeout: 5000

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3