require_relative 'piece'
require_relative 'piece/rook'
require_relative 'piece/bishop'
require_relative 'piece/queen'
require_relative 'piece/king'
require_relative 'piece/knight'
require_relative 'piece/empty'
# require_relative 'piece/pawn'
